sonar.projectKey=front.phone
sonar.projectName=front.phone
sonar.projectVersion=4.21.0

sonar.sources=src/script
sonar.tests=spec
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/bin/**,**/obj/**,**/*.generated.*,**/coverage/**
sonar.test.inclusions=spec/**/*-spec.coffee,**/*.test.*,**/*.spec.*,**/__tests__/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=spec/**,**/*-spec.coffee,Gruntfile.coffee,src/script/main.coffee
